### PR TITLE
Include elasticsearch-logging to fix `NoClassDefFoundError: org/elasticsearch/logging/LogManager` error

### LINKED ISSUE #440: Sync up 8.19 and release
(_always confusion: 8.19 plugin bridge doesn't use `logstash-bridge` but 9.x/main branches do_)

Some clarifications: 8.19 branch didn't use ES logging module but main branch does. Even though we have a bridge for logging interfaces introduced by https://github.com/elastic/elasticsearch/pull/145830 but 8.19 doesn't use the bridge, so no need a backport.

The upstream ES change introduced a logging dependency - https://github.com/elastic/elasticsearch/pull/145588
where the plugin 8.19 should include the module to successfully compile and build.

### PR DESCRIPTION
**Pull request by mashhurs**
[Error logs](https://buildkite.com/elastic/logstash-filter-elastic-integration-build/builds/1006#019d642a-5773-4284-a03c-aee89bce915b):
```
2026-04-06 12:26:12 PDT | logstash-1       \|         expected no Exception, got #<Java::JavaLang::NoClassDefFoundError: Could not initialize class org.elasticsearch.common.cache.Cache> with backtrace:
-- | --
2026-04-06 12:26:12 PDT | logstash-1       \|           # org.elasticsearch.common.cache.CacheBuilder.build(CacheBuilder.java:83)
2026-04-06 12:26:12 PDT | logstash-1       \|           # org.elasticsearch.script.ScriptCache.<init>(ScriptCache.java:70)
2026-04-06 12:26:12 PDT | logstash-1       \|           # org.elasticsearch.script.ScriptService$CacheHolder.<init>(ScriptService.java:915)
2026-04-06 12:26:12 PDT | logstash-1       \|           # org.elasticsearch.script.ScriptService.generalCacheHolder(ScriptService.java:861)
2026-04-06 12:26:12 PDT | logstash-1       \|           # org.elasticsearch.script.ScriptService.setCacheHolder(ScriptService.java:830)

2026-04-06 12:26:12 PDT | logstash-1       \|       # --- Caused by: ---
-- | --
2026-04-06 12:26:12 PDT | logstash-1       \|       # Java::JavaLang::ExceptionInInitializerError:
2026-04-06 12:26:12 PDT | logstash-1       \|       #   Exception java.lang.NoClassDefFoundError: org/elasticsearch/logging/LogManager [in thread "main"]
2026-04-06 12:26:12 PDT | logstash-1       \|       #   org.elasticsearch.common.cache.Cache.<clinit>(Cache.java:65)


```

### CODE REVIEW

File: src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java [hunk 1]
```diff
@@ -67,6 +68,10 @@
 @SuppressWarnings("UnusedReturnValue")
 public class EventProcessorBuilder {
 
+    static {
+        LogConfigurator.configureESLogging();
```
Comment (mashhurs) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java:72]: Similar what we have in logstash-bridge (plugin 9.x/main branch uses) - https://github.com/elastic/elasticsearch/blob/main/libs/logstash-bridge/src/main/java/org/elasticsearch/logstashbridge/common/LoggingBridge.java

Comment (yaauie) [reply src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java:72]: It's what we have [on current `main`](https://github.com/elastic/logstash-filter-elastic_integration/blob/9487d6db5173659216cc58025f2a36c3f1598c39/src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java#L51-L54), too. 

It looks like `main` doesn't _use_ that bridge bit yet either.

**Review by yaauie — APPROVED** [review]

**Review by donoghuc — APPROVED** [review]
nice
